name: reviewdog-checkstyle
on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  checkstyle-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: backend
          reporter: github-pr-review        # ← inline review komentarji
          filter_mode: added                # ← samo dodane vrstice v PR-ju
          fail_level: none                  # ← ne failaj joba zaradi kršitev

  eslint-frontend:
    name: ESLint (frontend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-

      - run: npm ci

      # ESLint + reviewdog → inline PR komentarji samo za dodane vrstice
      - name: ESLint via reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: frontend
          reporter: github-pr-review
          filter_mode: added
          fail_on_error: 'false'
          eslint_flags: '--ext .js,.jsx,.ts,.tsx .'
          
  jacoco:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Build & Test with Coverage
        working-directory: backend
        run: mvn -B clean verify -Pcoverage

      - name: Jacoco Report
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: backend/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 60
          min-coverage-changed-files: 80

