name: reviewdog-checkstyle
on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  checkstyle-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: backend
          reporter: github-pr-review        # ← inline review komentarji
          filter_mode: added                # ← samo dodane vrstice v PR-ju
          fail_level: none                  # ← ne failaj joba zaradi kršitev
